pew/shell_config/init.bash
The final reset marker `\e[0m` is not wrapped in `\[\]` which leads to issues in prompt size computation. This introduce unpredictible behaviors, e.g., when the input is near the end of the line (see picture below):
The issue had been observed with:
* xterm
* terminology
The fix had been tested with:
* xterm
* terminology
=> Wraps reset marker in '\[\]'

pew/pew.py
Sorting the lists and having file paths on separate lines
makes it easy visually to verify the items.
=> Sorted package lists and files

pew/pew.py
Improve the `source_cmd` check to also validate indented source command like:
if type -q pew
source (pew shell_config)
end
=> allow source command indentation in shell rc

pew/pew.py
This file is not exectuable, and even if it were it doesn't do anything
useful when executed on its own.
This came up in the review to include pew in Fedora.
=> Remove unnecessary shebang

pew/pew.py, tests/test_workon.py
Eventually, I think it would be better for `parse_envname()` to just raise `KeyError` or similar, in which case we could `lsvirtualenv()` or err out appropriately.  Passing the `no_arg_callback` seems strange.
However, this at least fixes the immediate issue.  Includes basic unit test.
=> Fix IndexError when calling "workon" with no argument, #137.

pew/pew.py, tests/conftest.py, tests/test_mkvirtualenv.py
For creating virtualenvs, pew used to cd into `WORKON_HOME` and then invoke `virtualenv`. If `WORKON_HOME` happens to be in a symlinked directory, the path resolution will consider the real path, not the symlinked one. If the symlink target changes at a later time, all the shebangs that use the real path, which is now obsolete, will be broken.
Eg. if `WORKON_HOME` is `/home/user/.local/venvs` and `/home/user/.local` is a symlink to `/opt/local`,
then current pew will create the virtualenv with `/opt/local` as the root, thus creating scripts with `#!/opt/local/venvs/foo/bin/python` instead of `#!/home/user/.local/venvs/foo/bin/python`
Before:
>>> check_call(['virtualenv', 'foo'], cwd='/home/user/.local/venvs')
New python executable in /opt/local/venvs/foo/bin/python
This patch changes the …
=> Fix virtualenv creation when WORKON_HOME lives within a symlink dir

Pipfile, pew/pew.py, requirements.txt, setup.py
So the tasklist method of looking up the parent id's name works only if the python executable runs the script directly, but since this is a cli util, `pew.exe` is the parent process, not the shell.  The shell is the grandparent of the `pew.exe`.  I also realized that `os.getppid()` doesn't work on windows on 2.x however there is a package, `psutil` that can help us out!  I can have it get the parent id of the `pew.exe` executable and it offers a polyfill for `os.getppid()` for python 2.7.  I've also made it so that it only gets installed on windows machines not any, since it only gets imported and used in windows.
=> Windows fixes

pew/pew.py
Python 2.x on Windows does not have os.getppid(), use os.getpid() and psutil instead.
=> Python 2.x compat for Windows shell detection

pew/__init__.py, pew/pew.py
This looks a little silly. What's happening here is that `pkg_resources` is quite slow to import – something like 200 ms or more on my system. This makes `pew in` feel sluggish when running commands that should be quick.
This PR takes the most direct approach of moving the `pkg_resources` import into the version command, which is the only consumer.
We could also switch `setup.py` to use a regex to read from `pew/__init__.py`, as many other packages do, if you would prefer that.
=> Defer pkg_resources import

tests/test_cp.py
Execution of virtualenv was  changed  to "python -m" style in https://github.com/berdario/pew/commit/999674cdf4e6e82758b4c8e97abf28e1ed5780bd, it would be nice to do the same in tests to keep it consistent.
=> Use -m to run virtualenv in tests as well

tests/test_restore.py
On Fedora it is common that `/tmp/WORKON_HOME/env1/lib64/` is a symlink to `/tmp/WORKON_HOME/env1/lib/`.
In case 
```
/tmp/WORKON_HOME/env1/lib/python3.6/site.py and
/tmp/WORKON_HOME/env1/lib64/python3.6/site.py
```
appear in `to_be_deleted_set`, file is removed when unlink() is called for the first time and `test_restore` fails in the second iteration with `FileNotFoundError.` I think this can be safely ignored.
=> Ignore FileNotFoundError in case to_be_deleted set in test_restore

tests/test_install.py
It seems also this test cannot run without network connection.
=> Add connection_required marker to Pythonz install test

pew/shell_config/init.bash
Before:
VEhost ~ $
After:
VE host ~ $
=> Put a space after VIRTUAL_ENV basename

pew/_print_utils.py, tests/test_print_utils.py
Some combinations of short and long env names caused the list to be split across too many columns. This in turn caused some lines in the list to wrap onto multiple lines, breaking the nice table.
=> Fix virtualenv list wrapping with long env names

README.md, pew/pew.py
This PR implements #179. 
It adds an optional argument for ``pew workon`` (``--here``) that prevents the current directory to be changed.
=> Add --here option for pew workon to prevent current directory to be changed

.travis.yml
Python 3.3 reached EOL a couple of months ago, and setuptools dropped support
for it earlier this year: pypa/setuptools@7392f01ff . As a result, the 3.3 entry in the
build matrix has been erroring out since at least #196.
=> Drop EOL'd Python 3.3 from Travis builds

Pipfile, pew/pew.py, requirements.txt, setup.py, tests/test_workon.py
Close #182.
Detection logic based on [Shellingham’s documentation](https://github.com/sarugaku/shellingham#notes-for-application-developers).
=> Use Shellingham for shell detection on Windows

README.md, pew/pew.py, tests/test_getproject.py
Use `pew getproject [env]` to print the given virtualenv's project directory, if one has been set.  If the `env` parameter is omitted, use the currently active virtualenv.
=> Add `getproject` command

README.md, pew/pew.py
Use argparse only and preserve --here option
Bonus: `pew workon` without an `envname` displays all available environments, instead of an error.
=> Use argparse for pew workon

pew/pew.py
This makes this line behave predictably with no assumptions on what
characters might be present in the path `pew` is installed in.
=> Quote properly in first_run_setup config line

pew/pew.py
Before:
```
$ pew list_pythons
Traceback (most recent call last):
File "/usr/sbin/pew", line 11, in <module>
load_entry_point('pew==1.1.5', 'console_scripts', 'pew')()
File "/usr/lib/python3.7/site-packages/pew/pew.py", line 758, in pew
return command(sys.argv[2:])
File "/usr/lib/python3.7/site-packages/pew/pew.py", line 662, in list_pythons_cmd
Path(PATH_PYTHONS).mkdir(parents=True)
NameError: name 'PATH_PYTHONS' is not defined
```
After:
```
$ pew list_pythons
You need to install the pythonz extra.  pip install pew[pythonz]
```
=> Fix list_pythons crash when Pythonz is not installed.

pew/shell_config/init.bash
Before:
$ echo "$PS1"
\[\033[01;34m\]$(basename '/home/greg/.local/share/virtualenvs/jupyter')\[\e[0m\] ...old PS1...
After:
$ echo "$PS1"
\[\033[01;34m\]jupyter\[\e[0m\] ...old PS1...
This is simpler, and moreover avoids the need to fork and exec
a `/usr/bin/basename` process each time the prompt is printed.
=> Compute basename eagerly for Bash prompt

pew/pew.py
Hello,
Currently, when running `pew --help`, the setproject command documentation is truncated. This PR fixes this.
Before:
```
pew
Available commands:
[...]
setproject:               Given a virtualenv directory and a project directory, set the
```
After:
```
pew
Available commands:
[...]
setproject:               Given a virtualenv directory and a project directory, set the virtualenv up to be associated with the project.
```
Thank you for this usefull cli! 
Maxime
=> Fix setproject_cmd documentation

README.md, pew/pew.py
There is a small typo in pew/pew.py.
Should read `available` rather than `avaiable`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, avaiable -> available

README.md
There is a small typo in README.md.
Should read `directories` rather than `directiories`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, directiories -> directories
